services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sawin
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    expose:
      - 5432